disseminate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.shortcuts import redirect
from app.views import DisplayListView, DisplayCreateView, DisplayUpdateView, DisplayDeleteView, FileCreateView, FileListView, manage_file_assignments, FileDeleteView

urlpatterns = [
    path('', lambda request: redirect('file-list', permanent=False)),  # Redirect root URL to /files/
    path('admin/', admin.site.urls),
    path('displays/', DisplayListView.as_view(), name='display-list'),
    path('displays/add/', DisplayCreateView.as_view(), name='display-add'),
    path('displays/<int:pk>/edit/', DisplayUpdateView.as_view(), name='display-edit'),
    path('displays/<int:pk>/delete/', DisplayDeleteView.as_view(), name='display-delete'),
    path('files/', FileListView.as_view(), name='file-list'),
    path('files/upload/', FileCreateView.as_view(), name='file-upload'),
    path('files/<int:file_id>/assign/', manage_file_assignments, name='manage-file-assignments'),
    path('files/<int:pk>/delete/', FileDeleteView.as_view(), name='file-delete')
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#else:
#    quit()

app/models.py
from django.db import models
from django.conf import settings
from PIL import Image
import subprocess
import os
import sys
from django.core.validators import RegexValidator

ip_validator = RegexValidator(r"^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$", "IP address must of format 'x.x.x.x'.")
remote_directory_validator = RegexValidator(r"^[0-9a-zA-Z/\-_]+$", "Directory may only contain '0-9a-zA-Z/-_'.")
username_password_validator = RegexValidator(r"^[0-9a-zA-Z/\-_]+$", "Value may only contain '0-9a-zA-Z/.-_'.")

class Display(models.Model):
    name = models.CharField(max_length=100)
    ip_address = models.CharField(max_length=100, validators=[ip_validator])
    username = models.CharField(max_length=100, validators=[username_password_validator])
    ssh_public_key_or_password = models.TextField(validators=[username_password_validator])
    remote_directory = models.CharField(max_length=255, validators=[remote_directory_validator])
    assigned_files = models.ManyToManyField('File', related_name='assigned_displays', blank=True)

    def __str__(self):
        return self.name

class File(models.Model):
    name = models.CharField(max_length=255)
    file = models.FileField(upload_to='.')
    displays = models.ManyToManyField('Display', related_name='files', blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.compress_image()
        for display in Display.objects.all():
            self.sync_media(display)
            self.restart_viewer(display)

    def delete(self, *args, **kwargs):
        try:
            os.remove(self.file.path)
        except:
            pass
        for display in Display.objects.all():
            self.sync_media(display)
            self.restart_viewer(display)
        super().delete(*args, **kwargs)

    def compress_image(self):
        img = Image.open(self.file.path)
        #img = Image.open(f"{settings.MEDIA_ROOT}{self.file.name}")
        max_width, max_height = 1280, 720
        scaling_factor = min(max_width / img.width, max_height / img.height)
        new_size = (int(img.width * scaling_factor), int(img.height * scaling_factor))
        img = img.resize(new_size, Image.Resampling.LANCZOS)
        img.save(self.file.path)

    def sync_media(self, display):
        display_cred = os.environ["DISPLAY_CRED"]
        command = f"sshpass -p {display_cred} rsync -e 'ssh -o StrictHostKeyChecking=no' -avu --delete {settings.MEDIA_ROOT} {display.username}@{display.ip_address}:{display.remote_directory}/"
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        # Check if the command was successful
        if result.returncode == 0:
            print("Sync completed for {display.name} successfully.", file=sys.stdout)
            #print(result.stdout, file=sys.stdout)
        else:
            print("Sync failed for {display.name}. Error message:", file=sys.stderr)
            print(result.stderr, file=sys.stderr)

    def restart_viewer(self, display):
        display_cred = os.environ["DISPLAY_CRED"]
        command = f"sshpass -p {display_cred} ssh -o StrictHostKeyChecking=no {display.username}@{display.ip_address} 'sudo killall fbi; sudo fbi --noverbose -T 1 -a -t 5 {display.remote_directory}/media/*'"
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        # Check if the command was successful
        if result.returncode == 0:
            print("Viewer started on {display.name} successfully.", file=sys.stdout)
            #print(result.stdout, file=sys.stdout)
        else:
            print("Viewer start failed for {display.name}. Error message:", file=sys.stderr)
            print(result.stderr, file=sys.stderr)

app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import File, Display
from django.forms import Textarea
from django import forms
from .decorators import basicauth
from django.utils.decorators import method_decorator


class DisplayForm(forms.ModelForm):
    class Meta:
        model = Display
        fields = (
            'name',
            'ip_address',
            'username',
            'ssh_public_key_or_password',
            'remote_directory',
        )
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'ip_address': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'ssh_public_key_or_password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'remote_directory': forms.TextInput(attrs={'class': 'form-control'}),
        }

@method_decorator(basicauth, name='dispatch')
class DisplayListView(ListView):
    model = Display
    template_name = 'display/display_list.html'
    context_object_name = 'displays'

@method_decorator(basicauth, name='dispatch')
class DisplayCreateView(CreateView):
    model = Display
    template_name = 'display/display_form.html'
    success_url = reverse_lazy('display-list')
    form_class = DisplayForm

@method_decorator(basicauth, name='dispatch')
class DisplayUpdateView(UpdateView):
    model = Display
    template_name = 'display/display_form.html'
    success_url = reverse_lazy('display-list')
    form_class = DisplayForm

@method_decorator(basicauth, name='dispatch')
class DisplayDeleteView(DeleteView):
    model = Display
    template_name = 'display/display_confirm_delete.html'
    success_url = reverse_lazy('display-list')

@method_decorator(basicauth, name='dispatch')
class FileListView(ListView):
    model = File
    template_name = 'file/file_list.html'
    context_object_name = 'files'

@basicauth
def manage_file_assignments(request, file_id):
    file = File.objects.get(pk=file_id)
    if request.method == 'POST':
        display_ids = request.POST.getlist('displays')
        displays = Display.objects.filter(pk__in=display_ids)
        file.displays.set(displays)
        return redirect('file-list')
    else:
        displays = Display.objects.all()
        assigned_displays = file.displays.all()
        return render(request, 'file/manage_file_assignments.html', {'file': file, 'displays': displays, 'assigned_displays': assigned_displays})

@method_decorator(basicauth, name='dispatch')
class FileCreateView(CreateView):
    model = File
    fields = ['name', 'file']
    template_name = 'file/file_form.html'

    def form_valid(self, form):
        self.object = form.save()
        return redirect('file-list')

@method_decorator(basicauth, name='dispatch')
class FileDeleteView(DeleteView):
    model = File
    template_name = 'file/file_confirm_delete.html'  # You can create this template for confirmation
    success_url = reverse_lazy('file-list')  # Redirect to the file list after deletion

app/templates/display/display_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Confirm Delete</title>
</head>
<body>
    <h1>Confirm Delete</h1>
    <p>Are you sure you want to delete <b>{{ display }}</b>?</p>
    <form method="post">
        {% csrf_token %}
        <div class="btn-toolbar" role="toolbar">
            <div class="btn-group me-2" role="group">
                <button type="submit" class="btn btn-danger">Confirm</button>
            </div>
            <div class="btn-group me-2" role="group">
                <a href="{% url 'display-list' %}" class="btn btn-secondary" role="button">Cancel</a>
            </div>
    </form>
</body>
</html>

app/templates/display/display_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{% if display %}Edit Display{% else %}Add Display{% endif %}</title>
</head>
<body>
    <h1>{% if display %}Edit Display{% else %}Add Display{% endif %}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="fieldWrapper">
            <label for="{{ form.name.id_for_label }}" class="form-label">Name:</label>
            {{ form.name.errors }}
            {{ form.name }}
        </div>

        <div class="fieldWrapper">
            <label for="{{ form.ip_address.id_for_label }}" class="form-label">IP:</label>
            {{ form.ip_address.errors }}
            {{ form.ip_address }}
        </div>

        <div class="fieldWrapper">
            <label for="{{ form.username.id_for_label }}" class="form-label">Username:</label>
            {{ form.username.errors }}
            {{ form.username }}
        </div>

        <div class="fieldWrapper">
            <label for="{{ form.ssh_public_key_or_password.id_for_label }}" class="form-label">Public Key/Password:</label>
            {{ form.ssh_public_key_or_password.errors }}
            {{ form.ssh_public_key_or_password }}
        </div>

        <div class="fieldWrapper">
            <label for="{{ form.remote_directory.id_for_label }}" class="form-label">Remote Directory:</label>
            {{ form.remote_directory.errors }}
            {{ form.remote_directory }}
        </div>

        <div class="btn-toolbar" role="toolbar">
            <div class="btn-group me-2" role="group">
                <button type="submit" class="btn btn-primary" role="button">Save</button>
            </div>
            <div class="btn-group me-2" role="group">
                <a href="{% url 'display-list' %}"><button type="button" class="btn btn-secondary" role="button">Cancel</button></a>
            </div>
        </div>
    </form>
</body>
</html>

app/templates/display/display_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Display List</title>
</head>
<body>
    <h1>Display List</h1>
    <div class="btn-toolbar" role="toolbar">
        <div class="btn-group me-2" role="group">
            <a href="{% url 'file-list' %}" class="btn btn-secondary">Go to Files</a> <!-- Link to the files page -->
        </div>
        <div class="btn-group me-2" role="group">
            <a href="{% url 'display-add' %}" class="btn btn-primary">Add Display</a>
        </div>
    </div>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">IP</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
        {% for display in displays %}
        <tr>
            <th scope="row">{{ display.name }}</th>
            <td>{{ display.ip_address }}</td>
            <td>
                <a href="{% url 'display-edit' display.pk %}">Edit</a><br/>
                <a href="{% url 'display-delete' display.pk %}">Delete</a>
            </td>
        {% empty %}
            <td>No displays found</td>
        {% endfor %}
    </tbody>
</table>
</body>
</html>

app/templates/file/file_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Delete File</title>
</head>
<body>
    <h1>Delete File</h1>
    <p>Are you sure you want to delete the file <b>{{ object.name }}</b>?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirm</button>
        <a href="{% url 'file-list' %}" class="btn btn-secondary" role="button">Cancel</a>
    </form>
</body>
</html>

app/templates/file/file_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Upload File</title>
</head>
<body>
    <h1>Upload File</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="filename" class="form-label">File Name</label>
            <input id="filename" class="form-control" type="text" name="name" maxlength="255" required="" id="id_name">
        </div>
        <div class="mb-3">
            <label for="id_file" class="form-label">File</label>
            <input type="file" class="form-control" name="file" required="" id="id_file">
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Upload</button>
        </div>
    </form>
</body>
</html>

app/templates/file/file_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>File List</title>
    <style>
        .file-item {
            display: flex;
            align-items: center;
        }
        .file-details {
            flex: 1;
        }
        .file-image {
            margin-left: 20px;
        }
        .file-image img {
            max-width: 200px;
            max-height: 200px;
        }
    </style>
</head>
<body>
    <h1>File List</h1>
    <div class="btn-toolbar" role="toolbar">
        <div class="btn-group me-2" role="group">
            <a href="{% url 'display-list' %}" class="btn btn-secondary">Go to Displays</a>
        </div>
        <div class="btn-group me-2" role="group">
            <a href="{% url 'file-upload' %}" class="btn btn-primary">Upload File</a>
        </div>
    </div>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">File</th>
            <th scope="col">Display</th>
            <th scope="col">Actions</th>
            <th scope="col">Preview</th>
          </tr>
        </thead>
        <tbody>
        {% for file in files %}
        <tr>
            <th scope="row">{{ file.name }}</th>
                <td>
                    <ul>
                        {% for display in file.displays.all %}
                            <li>{{ display.name }}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <a href="{% url 'manage-file-assignments' file.id %}">
                        Assign to Displays
                      </a><br/>
                <a href="{% url 'file-delete' pk=file.id %}">Delete
                </a></td>
                <td>
                <div class="file-image">
                    {% if file.file.url %}
                        <img src="{{ file.file.url }}" alt="{{ file.name }}">
                    {% endif %}
                </div>
            </td>
        {% empty %}
            <td>No files found</td>
        {% endfor %}
        </tbody>
    </table>
</body>
</html>

app/templates/file/manage_file_assignments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Manage File Assignments</title>
</head>
<body>
    <h1>Manage Assignments for "{{ file }}"</h1>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="displays" class="form-label">Select Display(s):</label>
        <select name="displays" multiple class="form-select" id="displays">
            {% for display in displays %}
                <option value="{{ display.id }}" {% if display in assigned_displays %}selected{% endif %}>{{ display.name }}</option>
            {% endfor %}
        </select>
        </div>
        <button type="submit" class="btn btn-primary">Assign</button>
    </form>
</body>
</html>